[package]
name = "eml_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
mail-parser = { version = "0.10.2", features = ["serde_support"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"