name: EML Extracto
services:
  devcontainer:
    container_name: eml_extractor
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    volumes:
      - ..:/app/
      - ~/.aws:/home/vscode/.aws # for awscli and aws-sdk-rust
    environment:
      - USER=chukwudi
    tty: true
